### ISSUE TITLE
how to get the points as trancos.py for training 

### ISSUE THREAD

**Issue by tongpinmo** [ElementAI/LCFCN#11]
now i want to train on my own dataset.I have read the trancos.py,pascal.py,shanghai.py.my dataset consists of images and their center point coordinates.In the trancos.py and shanghai.py line 46,we can see they all have the .mat files ,what should I do to prepare the points without ROI and  .mat files ? I am really confused

**Comment by tongpinmo** [comment]
@IssamLaradji

**Comment by tongpinmo** [comment]
I just have the center point files and images ,how to do? should  I create the .mat files and dots.png?

**Comment by tongpinmo** [comment]
ok,i got it

**Comment by GloriaZLQ** [comment]
> ok,i got it

how do you get it???
i want to train on my own dataset too.

**Comment by GloriaZLQ** [comment]
@tongpinmo
