### ISSUE TITLE
How to use best_model_pascal_ResFCN.pth?

### ISSUE THREAD

**Issue by SJLNNU** [ElementAI/LCFCN#12]
HI,
   After i use command "
  python3 main.py -image_path figures/test.png                
 -model_path checkpoints/best_model_pascal_ResFCN.pth                
 -model_name ResFCN"
I get this :
********************************************************************************
RuntimeError: Error(s) in loading state_dict for ResFCN:
        size mismatch for score_32s.bias: copying a param with shape torch.Size([21]) from checkpoint, the shape in current model is torch.Size([2]).
        size mismatch for score_32s.weight: copying a param with shape torch.Size([21, 2048, 1, 1]) from checkpoint, the shape in current model is torch.Size([2, 2048, 1, 1]).
        size mismatch for score_16s.bias: copying a param with shape torch.Size([21]) from checkpoint, the shape in current model is torch.Size([2]).
        size mismatch for score_16s.weight: copying a param with shape torch.Size([21, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([2, 1024, 1, 1]).
        size mismatch for score_8s.bias: copying a param with shape torch.Size([21]) from checkpoint, the shape in current model is torch.Size([2]).
        size mismatch for score_8s.weight: copying a param with shape torch.Size([21, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([2, 512, 1, 1]).
********************************************************
It seems  best_model_pascal_ResFCN.pth is not match for ResFCN.
Did i miss something? Can the best_model_pascal_ResFCN.pth work well  for detect pedestrian like the picture shown in the README.
Thanks

**Comment by GloriaZLQ** [comment]
have you solved it？

**Comment by GloriaZLQ** [comment]
i changed：model = model_dict[model_name](n_classes=21).cuda()
in applyonlmage.py

**Comment by GloriaZLQ** [comment]
i changed: # model = model_dict[model_name](n_classes=21).cuda()  
in applyonimage.py

**Comment by GloriaZLQ** [comment]
i changed:#n_classes=21

in applyonimage.py

**Comment by IssamLaradji** [comment]
Oh yah, this happens because there is a mismatch in the number of output classes. Pascal models expect 21 output categories whereas others could expect 2 output categories. Like what GloriaZLQ mentioned, you can modify `#n_classes` to  solve this.
