### ISSUE TITLE
when  run " bash checkpoints/download.sh"

### ISSUE THREAD

**Issue by GloriaZLQ** [ElementAI/LCFCN#13]
when i run " bash checkpoints/download.sh"there is a error:
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to www.dropbox.com port 443: Connection refused
Archive:  pascal_ResFCN.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of pascal_ResFCN.zip or
        pascal_ResFCN.zip.zip, and cannot find pascal_ResFCN.zip.ZIP, period.
mv: cannot stat 'pascal_ResFCN/State_Dicts/best_model.pth': No such file or directory
mv: cannot stat 'pascal_ResFCN/history.json': No such file or directory

**Comment by Jackandrome** [comment]
do you fix this problem?
