### ISSUE TITLE
What is p["cls"]??

### ISSUE THREAD

**Issue by akshitac8** [ElementAI/LCFCN#15]
Hey,

I am not able to understand the use case of this statement and what is p["cls"]?
```
points[int(p["y"]), int(p["x"])] = p["cls"]
```

**Comment by IssamLaradji** [comment]
Hii! `p["cls"]` is the category id of point `p`, which, as examples, can be for `horse`, `person`, and so on.

**Comment by akshitac8** [comment]
But in p there are only 3 keys: x,y, and name. There is no cls key

**Comment by IssamLaradji** [comment]
The `cls` key is only found in `self.pointsJSON` under `Pascal2007`. I didn't make the keys for the point `dicts` super consistent yet :(

**Comment by sirtris** [comment]
I guess the .json file for `self.pointsJSON` is created by the `get_pointDict` function if no .json file exists?
But the function returns a dict with `x, y, name` as keys. So are `name` and `cls` the same key or should the .json file be created in a different way?

**Comment by zyweven** [comment]
I don't understand what the role of p["cls"] is.I used Pascal2007, but the generated pointsJSON doesn't have p["cls"] , how should I handle it?
