### ISSUE TITLE
the question when train model on shanghaitech dataset

### ISSUE THREAD

**Issue by liubianting** [ElementAI/LCFCN#16]
when I want to train the model on shanghai dataset
always cause an Error:
.\datasets\shanghai.py,line 51, in __getitem__
points[int(y),int(x)] = 1
IndexError:index 1024 is out of bounds for axis 1 with size 1024

**Comment by w2933161** [comment]
File "/media/www/data1/wrb/LCFCN-master/datasets/shanghai.py", line 53, in __getitem__
    points[int(y), int(x)] = 1
IndexError: index 1125 is out of bounds for axis 1 with size 1024
me too

**Comment by w2933161** [comment]
数据集的问题，代码没问题

**Comment by IssamLaradji** [comment]
ah that happens because `int(x)` or `int(y)` are at the edge of the image, I added the following fix,
```
H, W = image.shape[:2]
for x, y in pointList:
     points[min(int(y), H-1), min(int(x), W-1)] = 1
``` 
If you are interested in the trained model for shanghai, this is the checkpoint for FCN8,
https://drive.google.com/file/d/1N75fun1I1XWh1LuKmi60QXF2SgCPLLLQ/view?usp=sharing
