### ISSUE TITLE
Convergence Properties

### ISSUE THREAD

**Issue by adrian-dalessandro** [ElementAI/LCFCN#19]
Under what conditions can we expect this model to converge? When I try to train the model on a different dataset, which has two classes (background and foreground) the model never predicts blobs. Instead, it will incorrectly make point predictions which mostly get pushes down by the false positive loss.

**Comment by IssamLaradji** [comment]
Did you try training the model on a single image? If the image resolution is high enough, the model should be able to predict blobs for the points given in that single image. 

If that image has a small resolution, like those in the UCSD dataset, then a common practice is to scale that image to a larger size. In this case, I would start by doubling the width and height of the dataset images.
