### ISSUE TITLE
How to annotate fro custom data training?

### ISSUE THREAD

**Issue by nathasha-naranpanawa** [ElementAI/LCFCN#31]
I have dataset of images with point annotations in the format of a JSON file. What is the format for annotations provided for LCFCN? Can I directly use (x,y) coordinates of the points or do I need to preprocess them to a different format?

**Comment by IssamLaradji** [comment]
For LCFCN, it needs points as a 2 dimensional array, where the first dimension is the height and the second is the width of the input image.

The array is zero in every entry except in the (x,y) coordinates of the points.

**Comment by nathasha-naranpanawa** [comment]
Thanks for the quick response! For the array entry at each (x,y) coordinate, should the value be the class number? For an example, if we have two classes 1-car and 2-person, would an array look something like this? 
0 0 0 0 0 
0 0 0 0 0 
0 1 0 0 0 
0 0 0 2 0
0 0 0 0 0

**Comment by IssamLaradji** [comment]
You welcome! The value is the class number indeed! The array looks correct.

**Comment by nathasha-naranpanawa** [comment]
That's great! Thanks!
