### ISSUE TITLE
Where are the path_model and path_opt files when training from scratch?

### ISSUE THREAD

**Issue by nathasha-naranpanawa** [ElementAI/LCFCN#32]
I'm trying to train for trancos from scratch. But checkpoints/model_trancos_ResFCN.pth
and checkpoints/opt_trancos_ResFCN.pth are missing, which throws FileNotFoundError when trying to train. Where do I get these files or how do I generate them?

**Comment by IssamLaradji** [comment]
did you try running the `checkpoints/download.sh` script? It should download those checkpoints.

**Comment by nathasha-naranpanawa** [comment]
I did. The downloaded folder only had the best_model.pth and history.json files.

**Comment by nathasha-naranpanawa** [comment]
This is what was provided to download Trancos checkpoints.
https://www.dropbox.com/sh/pwmoej499sfqb08/AABY13YraHYF51yw62Zc1w0-a?dl=0

And it only have the best_model.pth and history.json files. 

What am I missing? Can you please help?

**Comment by IssamLaradji** [comment]
Hi sorry about that. Can you use `best_model.pth` to load the model? it should be equivalent to `trancos_ResFCN.pth`. You can rename the `best_model.pth` to `trancos_ResFCN.pth`.

**Comment by IssamLaradji** [comment]
Why do you need the checkpoints if you are training from scratch?

**Comment by nathasha-naranpanawa** [comment]
Sorry I'm very new to deep learning. I thought since main.py needs all arhuments path_history, path_model, path_opt, path_best_model for training that those files were necessary. Do I not need them?

**Comment by IssamLaradji** [comment]
those paths are there in order to specify where they are saved. You don't need them.
The image below is part of `train.py`. It shows that if the path does not exist, then it won't be loaded.

![image](https://user-images.githubusercontent.com/3382128/79294460-3fe61100-7ea4-11ea-9cb0-ff19a887995a.png)

**Comment by nathasha-naranpanawa** [comment]
Thank you!
