### ISSUE TITLE
ValueError: exp_list is empty...

### ISSUE THREAD

**Issue by BJTUJia** [ElementAI/LCFCN#34]
Dear author, I am using the codes on my own dataset to count pigs. I am just starting now, the training seems fine. But when I try to visualize the dashboard in Jupyter notebook, it always reports the following error. 
![image](https://user-images.githubusercontent.com/24791613/85988859-3fc8cc80-ba22-11ea-93cb-c4425aadc98f.png)

Can you help me with this? Also, the command I use to train is  'python trainval.py -e piggy '.  I was able to set other parameters as their default value as:
![image](https://user-images.githubusercontent.com/24791613/85988819-317ab080-ba22-11ea-9dd2-cf8e6e14797f.png)

But if I set parser.add_argument('-e', '--exp_group_list',  default=piggy, nargs='+'), it always reports that the name 'piggy' is not defined. But the command line  'python trainval.py -e piggy ' works fine, which is pretty weird. Can you help me with this? Thanks very much.

**Comment by IssamLaradji** [comment]
in the jupyter script you showed me, the `savedir_base` should be `/export/chenlu/LCFCN-master/exp`. can you try that please?

**Comment by BJTUJia** [comment]
@IssamLaradji Thanks very much for your quick reply! The second problem is solved perfectly. As for the first one,  the 'exp_list is empty' error now is fixed with your solution. However,  another error occurs about   `filterby_list` = [('dataset.name','piggy')]` that says ` --> 684             if meta_dict.get('best'):
    685                 assert savedir_base is not None
    686                 el = filter_exp_list(exp_list, filterby_list=fd, verbose=verbose)

AttributeError: 'str' object has no attribute 'get'`. Am I giving the argument `'piggy'` in a wrong way？ It shouldn't be a string? Can you help me to figure this out? Thanks again!

**Comment by fhong-jpg** [comment]
@BJTUJia Have you solve the second problem？I'm facing the same one as you did. Please Help me if you solved it.
![image](https://user-images.githubusercontent.com/54538278/99613508-a5aa0500-2a52-11eb-8e6c-0acc1eab14fa.png)

**Comment by IssamLaradji** [comment]
@fhong-jpg @BJTUJia can you make `filterby_list=None` in the Jupyter cell? thanks

**Comment by fhong-jpg** [comment]
@IssamLaradji After I make filterby_list=None in the Jupyter cell, the last cell reported some errors:
![image](https://user-images.githubusercontent.com/54538278/99961173-e85c3c00-2dc8-11eb-8479-9814cdbb0787.png)

---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
~/anaconda3/envs/detectron2/lib/python3.7/site-packages/ipywidgets/widgets/widget_selection.py in findvalue(array, value, compare)
    136     try:
--> 137         return next(x for x in array if compare(x, value))
    138     except StopIteration:

StopIteration: 

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
~/anaconda3/envs/detectron2/lib/python3.7/site-packages/ipywidgets/widgets/widget_selection.py in _validate_value(self, proposal)
    368         try:
--> 369             return tuple(findvalue(self._options_values, i, self.equals) for i in proposal.value)
    370         except ValueError:

~/anaconda3/envs/detectron2/lib/python3.7/site-packages/ipywidgets/widgets/widget_selection.py in <genexpr>(.0)
    368         try:
--> 369             return tuple(findvalue(self._options_values, i, self.equals) for i in proposal.value)
    370         except ValueError:

~/anaconda3/envs/detectron2/lib/python3.7/site-packages/ipywidgets/widgets/widget_selection.py in findvalue(array, value, compare)
    138     except StopIteration:
--> 139         raise ValueError('%r not in array'%value)
    140 

ValueError: 'model.base' not in array

During handling of the above exception, another exception occurred:

TraitError                                Traceback (most recent call last)
~/anaconda3/envs/detectron2/lib/python3.7/site-packages/haven/haven_jupyter/__init__.py in display(self)
    129             # show tabs
    130             tables_tab(self, tables)
--> 131             plots_tab(self, plots)
    132             images_tab(self, images)
    133             share_tab(self, share)

~/anaconda3/envs/detectron2/lib/python3.7/site-packages/haven/haven_jupyter/plots_tab.py in plots_tab(self, output)
     27 def plots_tab(self, output):
     28     llegend_list = widgets.SelectMultiple(options=self.rm.exp_params,
---> 29                         value=self.vars.get('legend_list', [self.rm.exp_params[0]]))
     30     # widgets.Text(
     31     #     value=str(self.vars.get('legend_list', '[model]')),

~/anaconda3/envs/detectron2/lib/python3.7/site-packages/ipywidgets/widgets/widget_selection.py in __init__(self, *args, **kwargs)
    324         self._options_values = tuple(i[1] for i in options)
    325 
--> 326         super(_MultipleSelection, self).__init__(*args, **kwargs)
    327         self._initializing_traits_ = False
    328 

~/anaconda3/envs/detectron2/lib/python3.7/site-packages/ipywidgets/widgets/widget.py in __init__(self, **kwargs)
    410         """Public constructor"""
    411         self._model_id = kwargs.pop('model_id', None)
--> 412         super(Widget, self).__init__(**kwargs)
    413 
    414         Widget._call_widget_constructed(self)

~/anaconda3/envs/detectron2/lib/python3.7/site-packages/traitlets/traitlets.py in __init__(self, *args, **kwargs)
   1078                 else:
   1079                     # passthrough args that don't set traits to super
-> 1080                     super_kwargs[key] = value
   1081         try:
   1082             super(HasTraits, self).__init__(*super_args, **super_kwargs)

~/anaconda3/envs/detectron2/lib/python3.7/contextlib.py in __exit__(self, type, value, traceback)
    117         if type is None:
    118             try:
--> 119                 next(self.gen)
    120             except StopIteration:
    121                 return False

~/anaconda3/envs/detectron2/lib/python3.7/site-packages/traitlets/traitlets.py in hold_trait_notifications(self)
   1203                                 self._trait_values.pop(name)
   1204                 cache = {}
-> 1205                 raise e
   1206             finally:
   1207                 self._cross_validation_lock = False

~/anaconda3/envs/detectron2/lib/python3.7/site-packages/traitlets/traitlets.py in hold_trait_notifications(self)
   1189                 for name in list(cache.keys()):
   1190                     trait = getattr(self.__class__, name)
-> 1191                     value = trait._cross_validate(self, getattr(self, name))
   1192                     self.set_trait(name, value)
   1193             except TraitError as e:

~/anaconda3/envs/detectron2/lib/python3.7/site-packages/traitlets/traitlets.py in _cross_validate(self, obj, value)
    616         if self.name in obj._trait_validators:
    617             proposal = Bunch({'trait': self, 'value': value, 'owner': obj})
--> 618             value = obj._trait_validators[self.name](obj, proposal)
    619         elif hasattr(obj, '_%s_validate' % self.name):
    620             meth_name = '_%s_validate' % self.name

~/anaconda3/envs/detectron2/lib/python3.7/site-packages/traitlets/traitlets.py in __call__(self, *args, **kwargs)
    973         """Pass `*args` and `**kwargs` to the handler's function if it exists."""
    974         if hasattr(self, 'func'):
--> 975             return self.func(*args, **kwargs)
    976         else:
    977             return self._init_call(*args, **kwargs)

~/anaconda3/envs/detectron2/lib/python3.7/site-packages/ipywidgets/widgets/widget_selection.py in _validate_value(self, proposal)
    369             return tuple(findvalue(self._options_values, i, self.equals) for i in proposal.value)
    370         except ValueError:
--> 371             raise TraitError('Invalid selection: value not found')
    372 
    373     @observe('value')

TraitError: Invalid selection: value not found

**Comment by IssamLaradji** [comment]
ah that's annoying, sorry about that @fhong-jpg , I know what's happening. 

Can you install the latest `haven-ai` with this command? 

```
pip install --upgrade git+https://github.com/haven-ai/haven-ai
```

**Comment by fhong-jpg** [comment]
@IssamLaradji Great:-), that works!

**Comment by IssamLaradji** [comment]
great! I will close the issue, but let me know if i can help more
