### ISSUE TITLE
Can you kindly provide the scripts for testing and visualization of blobs?

### ISSUE THREAD

**Issue by BJTUJia** [ElementAI/LCFCN#35]
Dear author, thanks for this great repo. However, I find that there is only the trainval.py  script,  there are no codes to test on the trained model on the test sets. Can you kindly provide this? Also, can you show me how to visualize the blobs like in ..\results\test.png_blobs_count_32.png ? Thanks very much!

**Comment by IssamLaradji** [comment]
Hii, yes! I added `scripts/trainvis_on_image.py`. Run it and it will output the blobs with a heatmap :) like in `..\results\test.png_blobs_count_32.png`

**Comment by BJTUJia** [comment]
Thanks a lot! It works
