### ISSUE TITLE
Error in loading .pth

### ISSUE THREAD

**Issue by BJTUJia** [ElementAI/LCFCN#36]
Dear author, thanks for your nice repo. However,  I encountered this problem in loading saved model files: `model.load_state_dict(hu.torch_load(model_path)) ` This line reports this error: `AttributeError: 'LCFCN' object has no attribute 'model'. I tried several solutions, but all resulted in failure. Can you help me with this issue? Thanks very much! ps, my python version is 3.7.7.

**Comment by IssamLaradji** [comment]
sorry for this, I fixed the bug!

**Comment by BJTUJia** [comment]
thanks a lot!
