### ISSUE TITLE
Wrong output with other backbone networks

### ISSUE THREAD

**Issue by BJTUJia** [ElementAI/LCFCN#39]
Hi there, thanks very much for this nice work. However,  since the original fcn8_resnet is large,  when I tried the LCFCN loss with other backbone networks such as Unet and LinkNet in this link https://github.com/ternaus/robot-surgery-segmentation/blob/master/models.py or lightweight mobilenet,  the loss seems to be decreasing normally, but the predict output count is always 1, please refer to the figure attached. I debugged the codes and can't find out what's wrong. Can you give me any tips? Thanks very much!
![image](https://user-images.githubusercontent.com/24791613/101763409-b57cac80-3b19-11eb-8278-333948dbdd60.png)

**Comment by IssamLaradji** [comment]
Is the output of these networks binary or multi-class?

**Comment by BJTUJia** [comment]
@IssamLaradji The output is multi-class

**Comment by IssamLaradji** [comment]
Ah that explains it, multi-class is not supported well yet. I will look into it

**Comment by BJTUJia** [comment]
Okay, thanks a lot!
