### ISSUE TITLE
Inference script

### ISSUE THREAD

**Issue by ashok-arjun** [ElementAI/LCFCN#42]
Hi

Thanks for this wonderful work.

1. Is there an inference script for the Shanghai Tech B dataset that can iterate through each of the test images and return the metrics?

2. The inference script `test_on_image.py` seems to have an error: There is no variable or library that is called `ut` but `ut` is used in the script. Can you correct it?

3. Can you also provide an example to invoke the inference script `test_on_image.py` for a single image from Shanghai Tech B?

Thanks a lot.

**Comment by IssamLaradji** [comment]
Thanks for your kind words.

For 1 and 3 you can use `scripts/trainvis_on_image.py`. Download and load the Shanghai dataset, loop over its batches, and call `model.val_on_batch(batch)` to get the metrics and `model.vis_on_batch(batch)` to visualize.

I have added the `utils.py` file for (2), I hope the script works for you now!

**Comment by ashok-arjun** [comment]
Thanks a ton for your help, Issam!
