### ISSUE TITLE
Some questions about compute_image_loss function!

### ISSUE THREAD

**Issue by SongyiGao** [ElementAI/LCFCN#5]
![image](https://user-images.githubusercontent.com/17947507/51787955-dc929500-21b2-11e9-99d3-29872a839bed.png)
I want to know why use 2 in "S.view（n，k，h * w）.max（2)" . So my sense here is to pick two maximum values to compute the loss, why not 3 or 4?

**Comment by IssamLaradji** [comment]
@SongyiGao the `.max(2)` picks the maximum values across dimension `3`. In other words, it picks `k` maximum values across the `h * w` dimension.
