### ISSUE TITLE
the shanghai model

### ISSUE THREAD

**Issue by hxy1181501030** [ElementAI/LCFCN#6]
the checkpoints/download.sh does't include ShanghaiTech checkpoint, can you update it?  thanks very much!

**Comment by IssamLaradji** [comment]
I will update that after the ICCV deadline, sorry about that!

**Comment by chaoxuzju** [comment]
Hi! Can you update ShanghaiTench checkpoint? I need it too. Thanks very much!

**Comment by srikrvd** [comment]
Hi Issam, any update on the Shanghaitech checkpoint? Would be wonderful if you can load it. Thanks!

**Comment by priya-dwivedi** [comment]
Hi Issam, same request as above. Kindly release the Shanghai tech trained model.

**Comment by IssamLaradji** [comment]
Hi all! thanks for your interest! 
Here is the link to the Shanghai checkpoint:
https://drive.google.com/file/d/1N75fun1I1XWh1LuKmi60QXF2SgCPLLLQ/view?usp=sharing
