### ISSUE TITLE
About batch_size ang gpu

### ISSUE THREAD

**Issue by 100sby** [ElementAI/LCFCN#9]
Thanks for your code!I have two questions.
1.Is bs only set to 1?Because the speed is so slow,i want to increase bs,but when runs it can have orror.What's the problem?
2.When i use cpu the speed is slow with when i use gpu?Why?Where should i modify?

Thank you!

**Comment by IssamLaradji** [comment]
1. The code currently only supports batch size 1 :(, because it was easier to code it that way. We plan to allow bigger batch sizes in the future.

2. GPUs are way faster than CPUs for almost any deep learning method. Are you wondering why the CPU version is slower?

**Comment by 100sby** [comment]
> 1. The code currently only supports batch size 1 :(, because it was easier to code it that way. We plan to allow bigger batch sizes in the future.
> 2. GPUs are way faster than CPUs for almost any deep learning method. Are you wondering why the CPU version is slower?

Thanks for your code!And the last problem has been settled.
Recently,wo want to use LCFCN to train my own dateset.My dateset has only 1000 images and when i trained  about 100 epochs,the loss converges.I s this normal?Because your trancos dateset runs about 100epochs.
On the other hand, i want to get your advice.Should i cancel the test set and keep only the validation se
